# Generated by Django 5.2.9 on 2026-01-29 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL изображения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватное мероприятие')),
                ('registration_ends_at', models.DateTimeField(blank=True, help_text='Дата и время окончания регистрации участников', null=True, verbose_name='Дата окончания регистрации')),
                ('results_published_at', models.DateTimeField(blank=True, help_text='Дата и время публикации итогов события', null=True, verbose_name='Дата подведения итогов')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('agenda', 'Повестка дня'), ('presentation', 'Презентация'), ('document', 'Документ'), ('photo', 'Фотография'), ('video', 'Видеозапись'), ('audio', 'Аудиозапись'), ('result', 'Результаты'), ('other', 'Другое')], default='document', help_text='Для чего используется этот файл в контексте события', max_length=20, verbose_name='Категория файла')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание файла в контексте события', null=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, help_text='Доступен ли файл всем участникам события', verbose_name='Публичный доступ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прикрепления')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Файл события',
                'verbose_name_plural': 'Файлы событий',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('role', models.CharField(choices=[('participant', 'Участник'), ('owner', 'Владелец'), ('referee', 'Судья')], default='participant', max_length=20, verbose_name='Роль')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
            ],
            options={
                'verbose_name': 'Участник события',
                'verbose_name_plural': 'Участники событий',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineSessionsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='Название оффлайн-сессии или мероприятия', max_length=255, verbose_name='Название сессии')),
                ('start_time', models.DateTimeField(help_text='Дата и время начала сессии', verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, help_text='Дата и время окончания сессии', null=True, verbose_name='Время окончания')),
                ('session_notes', models.TextField(blank=True, help_text='Дополнительная информация, инструкции, заметки', null=True, verbose_name='Заметки к сессии')),
                ('address', models.CharField(blank=True, help_text='Полный адрес проведения мероприятия', max_length=500, null=True, verbose_name='Адрес')),
                ('room', models.CharField(blank=True, help_text='Номер кабинета, аудитории или зала', max_length=100, null=True, verbose_name='Кабинет/аудитория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('ongoing', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус сессии')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Максимальное количество участников для этой сессии', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум участников')),
            ],
            options={
                'verbose_name': 'Оффлайн-сессия',
                'verbose_name_plural': 'Оффлайн-сессии',
                'ordering': ['start_time', 'session_name'],
            },
        ),
        migrations.CreateModel(
            name='OnlineEventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='Название онлайн-сессии или мероприятия', max_length=255, verbose_name='Название сессии')),
                ('start_time', models.DateTimeField(help_text='Дата и время начала сессии', verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, help_text='Дата и время окончания сессии', null=True, verbose_name='Время окончания')),
                ('session_notes', models.TextField(blank=True, help_text='Дополнительная информация, инструкции, заметки', null=True, verbose_name='Заметки к сессии')),
                ('link', models.URLField(blank=True, help_text='Ссылка для подключения к онлайн-сессии', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('ongoing', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус сессии')),
                ('platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('webex', 'Webex'), ('jitsi', 'Jitsi'), ('other', 'Другая')], default='other', max_length=20, verbose_name='Платформа')),
                ('access_code', models.CharField(blank=True, help_text='Пароль или код для входа в сессию', max_length=100, null=True, verbose_name='Код доступа')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Максимальное количество участников для этой сессии', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум участников')),
            ],
            options={
                'verbose_name': 'Онлайн-сессия',
                'verbose_name_plural': 'Онлайн-сессии',
                'ordering': ['start_time', 'session_name'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Время присоединения')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('joined', 'Присоединился'), ('left', 'Вышел'), ('completed', 'Завершил'), ('no_show', 'Не явился')], default='registered', max_length=20, verbose_name='Статус участия')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Длительность присутствия (сек)')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Посещаемость сессии',
                'verbose_name_plural': 'Посещаемость сессий',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='session_materials/%Y/%m/%d/', verbose_name='Файл')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на файл')),
                ('material_type', models.CharField(choices=[('presentation', 'Презентация'), ('document', 'Документ'), ('video', 'Видео'), ('audio', 'Аудио'), ('link', 'Ссылка'), ('other', 'Другое')], default='document', max_length=20, verbose_name='Тип материала')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный доступ')),
            ],
            options={
                'verbose_name': 'Материал сессии',
                'verbose_name_plural': 'Материалы сессий',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
