# Generated by Django 5.2.9 on 2025-12-06 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL изображения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('role', models.CharField(choices=[('participant', 'Участник'), ('speaker', 'Докладчик'), ('organizer', 'Организатор'), ('volunteer', 'Волонтер')], default='participant', max_length=20, verbose_name='Роль')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник события',
                'verbose_name_plural': 'Участники событий',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineEventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='Название онлайн-сессии или мероприятия', max_length=255, verbose_name='Название сессии')),
                ('start_time', models.DateTimeField(help_text='Дата и время начала сессии', verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, help_text='Дата и время окончания сессии', null=True, verbose_name='Время окончания')),
                ('session_notes', models.TextField(blank=True, help_text='Дополнительная информация, инструкции, заметки', null=True, verbose_name='Заметки к сессии')),
                ('link', models.URLField(blank=True, help_text='Ссылка для подключения к онлайн-сессии', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('ongoing', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус сессии')),
                ('platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('webex', 'Webex'), ('jitsi', 'Jitsi'), ('other', 'Другая')], default='other', max_length=20, verbose_name='Платформа')),
                ('access_code', models.CharField(blank=True, help_text='Пароль или код для входа в сессию', max_length=100, null=True, verbose_name='Код доступа')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Максимальное количество участников для этой сессии', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум участников')),
                ('event', models.ForeignKey(help_text='Основное событие, к которому относится эта сессия', on_delete=django.db.models.deletion.CASCADE, related_name='online_sessions', to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Онлайн-сессия',
                'verbose_name_plural': 'Онлайн-сессии',
                'ordering': ['start_time', 'session_name'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Время присоединения')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('joined', 'Присоединился'), ('left', 'Вышел'), ('completed', 'Завершил'), ('no_show', 'Не явился')], default='registered', max_length=20, verbose_name='Статус участия')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Длительность присутствия (сек)')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.onlineeventinfo', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Посещаемость сессии',
                'verbose_name_plural': 'Посещаемость сессий',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='session_materials/%Y/%m/%d/', verbose_name='Файл')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на файл')),
                ('material_type', models.CharField(choices=[('presentation', 'Презентация'), ('document', 'Документ'), ('video', 'Видео'), ('audio', 'Аудио'), ('link', 'Ссылка'), ('other', 'Другое')], default='document', max_length=20, verbose_name='Тип материала')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный доступ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='events.onlineeventinfo', verbose_name='Сессия')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Материал сессии',
                'verbose_name_plural': 'Материалы сессий',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='events_even_created_52c227_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['closes_at'], name='events_even_closes__b4ea3a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'status'], name='events_even_owner_i_cf96c4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'user'], name='events_even_event_i_e2cef4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['is_confirmed'], name='events_even_is_conf_8ea949_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='onlineeventinfo',
            index=models.Index(fields=['event', 'start_time'], name='events_onli_event_i_57878c_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineeventinfo',
            index=models.Index(fields=['status'], name='events_onli_status_22f8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineeventinfo',
            index=models.Index(fields=['start_time'], name='events_onli_start_t_ca8e55_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineeventinfo',
            index=models.Index(fields=['event', 'status'], name='events_onli_event_i_131ef9_idx'),
        ),
        migrations.AddConstraint(
            model_name='onlineeventinfo',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('end_time__isnull', True), _connector='OR'), name='end_time_after_start_time'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session', 'participant'], name='events_sess_session_980602_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['status'], name='events_sess_status_729323_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['joined_at'], name='events_sess_joined__9b969f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'participant')},
        ),
        migrations.AddIndex(
            model_name='sessionmaterial',
            index=models.Index(fields=['session', 'material_type'], name='events_sess_session_38d46d_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmaterial',
            index=models.Index(fields=['uploaded_at'], name='events_sess_uploade_0b2a39_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmaterial',
            index=models.Index(fields=['is_public'], name='events_sess_is_publ_400126_idx'),
        ),
    ]
