# Generated by Django 5.2.9 on 2026-01-29 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='eventfile',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='events.event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='eventfile',
            name='storage_file',
            field=models.ForeignKey(help_text='Файл из файлового хранилища', on_delete=django.db.models.deletion.CASCADE, related_name='event_attachments', to='files.storagefile', verbose_name='Файл из хранилища'),
        ),
        migrations.AddField(
            model_name='eventfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_event_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='events.event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='offlinesessionsinfo',
            name='event',
            field=models.ForeignKey(help_text='Основное событие, к которому относится эта сессия', on_delete=django.db.models.deletion.CASCADE, related_name='offline_sessions', to='events.event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='onlineeventinfo',
            name='event',
            field=models.ForeignKey(help_text='Основное событие, к которому относится эта сессия', on_delete=django.db.models.deletion.CASCADE, related_name='online_sessions', to='events.event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.onlineeventinfo', verbose_name='Сессия'),
        ),
        migrations.AddField(
            model_name='sessionmaterial',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='events.onlineeventinfo', verbose_name='Сессия'),
        ),
        migrations.AddField(
            model_name='sessionmaterial',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='events_even_created_52c227_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['closes_at'], name='events_even_closes__b4ea3a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'status'], name='events_even_owner_i_cf96c4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_private'], name='events_even_is_priv_d7766c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfile',
            index=models.Index(fields=['event', 'category'], name='events_even_event_i_873339_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfile',
            index=models.Index(fields=['is_public'], name='events_even_is_publ_a4f746_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfile',
            index=models.Index(fields=['uploaded_at'], name='events_even_uploade_cfc948_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventfile',
            unique_together={('event', 'storage_file')},
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'user'], name='events_even_event_i_e2cef4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['is_confirmed'], name='events_even_is_conf_8ea949_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='offlinesessionsinfo',
            index=models.Index(fields=['event', 'start_time'], name='events_offl_event_i_3dc33c_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinesessionsinfo',
            index=models.Index(fields=['status'], name='events_offl_status_e22722_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinesessionsinfo',
            index=models.Index(fields=['start_time'], name='events_offl_start_t_ab7087_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinesessionsinfo',
            index=models.Index(fields=['event', 'status'], name='events_offl_event_i_a1ddc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='offlinesessionsinfo',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('end_time__isnull', True), _connector='OR'), name='offline_end_time_after_start_time'),
        ),
        migrations.AddIndex(
            model_name='onlineeventinfo',
            index=models.Index(fields=['event', 'start_time'], name='events_onli_event_i_57878c_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineeventinfo',
            index=models.Index(fields=['status'], name='events_onli_status_22f8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineeventinfo',
            index=models.Index(fields=['start_time'], name='events_onli_start_t_ca8e55_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineeventinfo',
            index=models.Index(fields=['event', 'status'], name='events_onli_event_i_131ef9_idx'),
        ),
        migrations.AddConstraint(
            model_name='onlineeventinfo',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('end_time__isnull', True), _connector='OR'), name='end_time_after_start_time'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session', 'participant'], name='events_sess_session_980602_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['status'], name='events_sess_status_729323_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['joined_at'], name='events_sess_joined__9b969f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'participant')},
        ),
        migrations.AddIndex(
            model_name='sessionmaterial',
            index=models.Index(fields=['session', 'material_type'], name='events_sess_session_38d46d_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmaterial',
            index=models.Index(fields=['uploaded_at'], name='events_sess_uploade_0b2a39_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmaterial',
            index=models.Index(fields=['is_public'], name='events_sess_is_publ_400126_idx'),
        ),
    ]
