# Generated by Django 5.2.9 on 2025-12-06 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='events.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('participant', 'Участник'), ('organizer', 'Организатор'), ('volunteer', 'Волонтер')], default='participant', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='OfflineSessionsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='Название оффлайн-сессии или мероприятия', max_length=255, verbose_name='Название сессии')),
                ('start_time', models.DateTimeField(help_text='Дата и время начала сессии', verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, help_text='Дата и время окончания сессии', null=True, verbose_name='Время окончания')),
                ('session_notes', models.TextField(blank=True, help_text='Дополнительная информация, инструкции, заметки', null=True, verbose_name='Заметки к сессии')),
                ('address', models.CharField(blank=True, help_text='Полный адрес проведения мероприятия', max_length=500, null=True, verbose_name='Адрес')),
                ('room', models.CharField(blank=True, help_text='Номер кабинета, аудитории или зала', max_length=100, null=True, verbose_name='Кабинет/аудитория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('ongoing', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус сессии')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Максимальное количество участников для этой сессии', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум участников')),
                ('event', models.ForeignKey(help_text='Основное событие, к которому относится эта сессия', on_delete=django.db.models.deletion.CASCADE, related_name='offline_sessions', to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Оффлайн-сессия',
                'verbose_name_plural': 'Оффлайн-сессии',
                'ordering': ['start_time', 'session_name'],
                'indexes': [models.Index(fields=['event', 'start_time'], name='events_offl_event_i_3dc33c_idx'), models.Index(fields=['status'], name='events_offl_status_e22722_idx'), models.Index(fields=['start_time'], name='events_offl_start_t_ab7087_idx'), models.Index(fields=['event', 'status'], name='events_offl_event_i_a1ddc8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('end_time__isnull', True), _connector='OR'), name='offline_end_time_after_start_time')],
            },
        ),
    ]
