# Generated by Django 5.2.9 on 2025-12-21 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventparticipant_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватное мероприятие'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_private'], name='events_even_is_priv_d7766c_idx'),
        ),
    ]
