# Generated by Django 5.2.9 on 2025-12-21 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_private_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('participant', 'Участник'), ('owner', 'Владелец'), ('referee', 'Судья')], default='participant', max_length=20, verbose_name='Роль'),
        ),
    ]
