# Generated by Django 5.2.9 on 2026-01-09 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_owner_alter_eventparticipant_role'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('agenda', 'Повестка дня'), ('presentation', 'Презентация'), ('document', 'Документ'), ('photo', 'Фотография'), ('video', 'Видеозапись'), ('audio', 'Аудиозапись'), ('result', 'Результаты'), ('other', 'Другое')], default='document', help_text='Для чего используется этот файл в контексте события', max_length=20, verbose_name='Категория файла')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание файла в контексте события', null=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, help_text='Доступен ли файл всем участникам события', verbose_name='Публичный доступ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прикрепления')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='events.event', verbose_name='Событие')),
                ('storage_file', models.ForeignKey(help_text='Файл из файлового хранилища', on_delete=django.db.models.deletion.CASCADE, related_name='event_attachments', to='files.storagefile', verbose_name='Файл из хранилища')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_event_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл события',
                'verbose_name_plural': 'Файлы событий',
                'ordering': ['display_order', '-uploaded_at'],
                'indexes': [models.Index(fields=['event', 'category'], name='events_even_event_i_873339_idx'), models.Index(fields=['is_public'], name='events_even_is_publ_a4f746_idx'), models.Index(fields=['uploaded_at'], name='events_even_uploade_cfc948_idx')],
                'unique_together': {('event', 'storage_file')},
            },
        ),
    ]
