# Generated by Django 5.2.9 on 2026-01-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_ends_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время окончания регистрации участников', null=True, verbose_name='Дата окончания регистрации'),
        ),
        migrations.AddField(
            model_name='event',
            name='results_published_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время публикации итогов события', null=True, verbose_name='Дата подведения итогов'),
        ),
    ]
