# Generated by Django 5.2.9 on 2025-12-02 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Пользователь с таким email уже существует.'}, max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='фамилия')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('student', 'Студент'), ('teacher', 'Учитель'), ('referee', 'Судья'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='роль')),
                ('phone', models.CharField(blank=True, error_messages={'unique': 'Пользователь с таким телефоном уже существует.'}, max_length=20, null=True, unique=True, verbose_name='телефон')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL аватара')),
                ('is_verified', models.BooleanField(default=False, verbose_name='подтвержден')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='user_user_email_5f6a77_idx'), models.Index(fields=['phone'], name='user_user_phone_8ad6f2_idx'), models.Index(fields=['role'], name='user_user_role_6c06b1_idx'), models.Index(fields=['created_at'], name='user_user_created_c7163e_idx'), models.Index(fields=['last_name', 'first_name'], name='user_user_last_na_2080cc_idx')],
            },
        ),
    ]
