# Generated by Django 5.2.9 on 2025-12-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('student', 'Студент'), ('teacher', 'Учитель'), ('referee', 'Судья')], default='user', max_length=20, verbose_name='роль'),
        ),
    ]
