# Generated by Django 5.2.9 on 2025-12-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='роль'),
        ),
    ]
