# Generated by Django 5.2.9 on 2026-01-09 20:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Человекочитаемое название файла', max_length=255, verbose_name='Название файла')),
                ('original_name', models.CharField(help_text='Оригинальное имя файла при загрузке', max_length=255, verbose_name='Оригинальное имя')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'mp4', 'avi', 'mov', 'mkv', 'mp3', 'wav', 'ogg', 'zip', 'rar', '7z', 'txt', 'csv', 'json', 'xml'])], verbose_name='Файл')),
                ('category', models.CharField(choices=[('image', 'Изображение'), ('document', 'Документ'), ('video', 'Видео'), ('audio', 'Аудио'), ('archive', 'Архив'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME тип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, help_text='Доступен ли файл для публичного просмотра', verbose_name='Публичный доступ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл в хранилище',
                'verbose_name_plural': 'Файлы в хранилище',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Токен доступа')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Если не указано, ссылка бессрочная', null=True, verbose_name='Действителен до')),
                ('max_downloads', models.PositiveIntegerField(default=0, help_text='0 = без ограничений', verbose_name='Максимум скачиваний')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Скачано раз')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='files.storagefile', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Ссылка для доступа',
                'verbose_name_plural': 'Ссылки для доступа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['category'], name='files_stora_categor_5c3286_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['is_public'], name='files_stora_is_publ_b42978_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['uploaded_by'], name='files_stora_uploade_54e9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['created_at'], name='files_stora_created_947a0e_idx'),
        ),
    ]
