# Generated by Django 5.2.9 on 2026-01-29 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filesharelink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='storagefile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='files.storagefile', verbose_name='Файл'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['category'], name='files_stora_categor_5c3286_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['is_public'], name='files_stora_is_publ_b42978_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['uploaded_by'], name='files_stora_uploade_54e9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['created_at'], name='files_stora_created_947a0e_idx'),
        ),
    ]
