# Generated by Django 5.2.9 on 2026-01-29 20:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, help_text='Средний арифметический балл всех участников', max_digits=3, null=True, verbose_name='Средний балл')),
                ('total_participants_rated', models.PositiveIntegerField(default=0, verbose_name='Всего участников с оценками')),
                ('total_ratings_given', models.PositiveIntegerField(default=0, verbose_name='Всего оценок выставлено')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Дата расчета статистики')),
            ],
            options={
                'verbose_name': 'Статистика события',
                'verbose_name_plural': 'Статистики событий',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.event', verbose_name='Событие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.eventparticipant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Оценка события',
                'verbose_name_plural': 'Оценки событий',
                'ordering': ['-created_at'],
            },
        ),
    ]
