# Generated by Django 5.2.9 on 2026-01-20 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_event_registration_ends_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название критерия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание критерия')),
                ('max_score', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальный балл')),
                ('weight', models.FloatField(default=1.0, help_text='Вес критерия в итоговой оценке (по умолчанию 1.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)], verbose_name='Вес критерия')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Критерий оценивания',
                'verbose_name_plural': 'Критерии оценивания',
                'ordering': ['order', 'name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название работы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание работы')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на файл')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('under_review', 'На проверке'), ('evaluated', 'Оценено'), ('rejected', 'Отклонено')], default='submitted', max_length=20, verbose_name='Статус работы')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='events.event', verbose_name='Мероприятие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_projects', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Работа участника',
                'verbose_name_plural': 'Работы участников',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Балл')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий судьи')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Судья')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_evaluations', to='events.onlineeventinfo', verbose_name='Сессия')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='stats.evaluationcriteria', verbose_name='Критерий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='stats.projectwork', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='StatisticSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('milestone', 'По вехам'), ('manual', 'Вручную')], max_length=50, verbose_name='Тип снимка')),
                ('data', models.JSONField(verbose_name='Данные снимка')),
                ('taken_at', models.DateTimeField(verbose_name='Время снимка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_snapshots', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Снимок статистики',
                'verbose_name_plural': 'Снимки статистики',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='CachedStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_type', models.CharField(choices=[('event_summary', 'Сводка по мероприятию'), ('rating_summary', 'Сводка по оценкам'), ('judge_consensus', 'Согласованность судей'), ('participant_stats', 'Статистика участников'), ('session_analytics', 'Аналитика сессий'), ('leaderboard', 'Текущий рейтинг'), ('weighted_avg', 'Взвешенное среднее'), ('trend_analysis', 'Анализ трендов')], max_length=50, verbose_name='Тип статистики')),
                ('data', models.JSONField(help_text='Рассчитанные результаты в формате JSON', verbose_name='Данные статистики')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Рассчитано')),
                ('expires_at', models.DateTimeField(help_text='Время инвалидации кэша', verbose_name='Истекает')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия данных')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_statistics', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Кэшированная статистика',
                'verbose_name_plural': 'Кэшированная статистика',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['event', 'statistic_type'], name='stats_cache_event_i_815ef8_idx'), models.Index(fields=['expires_at'], name='stats_cache_expires_4bf439_idx'), models.Index(fields=['calculated_at'], name='stats_cache_calcula_575e9c_idx')],
                'unique_together': {('event', 'statistic_type')},
            },
        ),
        migrations.CreateModel(
            name='JudgeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Вес оценки этого судьи при расчете взвешенного среднего', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)], verbose_name='Вес судьи')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Рассчитано')),
                ('calculation_method', models.CharField(choices=[('manual', 'Вручную'), ('consensus', 'По согласованности'), ('reputation', 'По репутации')], default='consensus', max_length=50, verbose_name='Метод расчета')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_weights', to='events.event', verbose_name='Мероприятие')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_weights', to=settings.AUTH_USER_MODEL, verbose_name='Судья')),
            ],
            options={
                'verbose_name': 'Вес судьи',
                'verbose_name_plural': 'Веса судей',
                'indexes': [models.Index(fields=['event', 'judge'], name='stats_judge_event_i_b261f8_idx'), models.Index(fields=['weight'], name='stats_judge_weight_edd21f_idx')],
                'unique_together': {('event', 'judge')},
            },
        ),
        migrations.AddIndex(
            model_name='projectwork',
            index=models.Index(fields=['event', 'participant'], name='stats_proje_event_i_13d01e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectwork',
            index=models.Index(fields=['status'], name='stats_proje_status_b43981_idx'),
        ),
        migrations.AddIndex(
            model_name='projectwork',
            index=models.Index(fields=['submitted_at'], name='stats_proje_submitt_f1b830_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectwork',
            unique_together={('event', 'participant')},
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['project', 'judge'], name='stats_evalu_project_067fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['is_confirmed'], name='stats_evalu_is_conf_527990_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluated_at'], name='stats_evalu_evaluat_cfa6d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('project', 'judge', 'criteria')},
        ),
        migrations.AddIndex(
            model_name='statisticsnapshot',
            index=models.Index(fields=['event', 'snapshot_type'], name='stats_stati_event_i_abb288_idx'),
        ),
        migrations.AddIndex(
            model_name='statisticsnapshot',
            index=models.Index(fields=['taken_at'], name='stats_stati_taken_a_24cc7f_idx'),
        ),
    ]
