# Generated by Django 5.2.9 on 2026-01-20 21:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_registration_ends_at_and_more'),
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AddField(
            model_name='projectwork',
            name='file',
            field=models.FileField(blank=True, help_text='Загруженный файл работы', null=True, upload_to='project_works/%Y/%m/%d/', verbose_name='Файл работы'),
        ),
        migrations.AlterField(
            model_name='cachedstatistic',
            name='expires_at',
            field=models.DateTimeField(help_text='Время, после которого данные считаются устаревшими', verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='cachedstatistic',
            name='statistic_type',
            field=models.CharField(choices=[('event_summary', 'Сводка по мероприятию'), ('rating_summary', 'Сводка по оценкам'), ('judge_consensus', 'Согласованность судей'), ('participant_stats', 'Статистика участников'), ('leaderboard', 'Текущий рейтинг'), ('weighted_avg', 'Взвешенное среднее')], max_length=50, verbose_name='Тип статистики'),
        ),
        migrations.AlterField(
            model_name='cachedstatistic',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='comment',
            field=models.TextField(blank=True, help_text='Обратная связь от судьи', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Когда оценка была подтверждена', null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='criteria',
            field=models.ForeignKey(help_text='Критерий, по которому выставляется оценка', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='stats.evaluationcriteria', verbose_name='Критерий'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Оценка подтверждена и финальна', verbose_name='Подтверждено'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='judge',
            field=models.ForeignKey(help_text='Пользователь, который выставляет оценку', on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Судья'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='project',
            field=models.ForeignKey(help_text='Работа, которую оценивают', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='stats.projectwork', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score',
            field=models.FloatField(help_text='Оценка по данному критерию', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Сессия, во время которой была выставлена оценка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_evaluations', to='events.onlineeventinfo', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='description',
            field=models.TextField(blank=True, help_text='Пояснение, что оценивается по этому критерию', null=True, verbose_name='Описание критерия'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='event',
            field=models.ForeignKey(help_text='Мероприятие, для которого настроены критерии', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Используется ли этот критерий при оценке', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='max_score',
            field=models.PositiveIntegerField(default=10, help_text='Максимально возможная оценка по этому критерию', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальный балл'),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения критериев (меньше = выше)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='projectwork',
            name='category',
            field=models.CharField(blank=True, help_text='Категория работы (опционально)', max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='projectwork',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projectwork',
            name='event',
            field=models.ForeignKey(help_text='Мероприятие, на которое загружена работа', on_delete=django.db.models.deletion.CASCADE, related_name='project_works', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='projectwork',
            name='file_url',
            field=models.URLField(blank=True, help_text='Ссылка на работу (Google Drive, Dropbox и т.д.)', max_length=500, null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='projectwork',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Видна ли работа судьям и другим участникам', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='projectwork',
            name='participant',
            field=models.ForeignKey(help_text='Пользователь, загрузивший работу', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_works', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AddIndex(
            model_name='evaluationcriteria',
            index=models.Index(fields=['event', 'is_active'], name='stats_evalu_event_i_33a1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcriteria',
            index=models.Index(fields=['order'], name='stats_evalu_order_a0fa9a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectwork',
            index=models.Index(fields=['is_published'], name='stats_proje_is_publ_4ca897_idx'),
        ),
    ]
