# Generated by Django 5.2.9 on 2026-01-29 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrating',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Судья'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='events.event', verbose_name='Событие'),
        ),
        migrations.AddIndex(
            model_name='eventrating',
            index=models.Index(fields=['event', 'participant'], name='stats_event_event_i_ad6ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrating',
            index=models.Index(fields=['referee'], name='stats_event_referee_7d5baa_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrating',
            index=models.Index(fields=['score'], name='stats_event_score_4329bb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrating',
            index=models.Index(fields=['created_at'], name='stats_event_created_f0c413_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrating',
            unique_together={('event', 'participant', 'referee')},
        ),
    ]
