# Generated by Django 5.2.9 on 2026-01-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrating',
            name='grading_system',
            field=models.CharField(choices=[('five_point', 'Пятибалльная система'), ('pass_fail', 'Зачет/незачет')], default='five_point', max_length=20, verbose_name='Система оценивания'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_fail',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество незачетов'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_1',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 1'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 2'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_3',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 3'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_4',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 4'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_5',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 5'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_pass',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество зачетов'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='most_popular_grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Наиболее часто встречающаяся оценка', null=True, verbose_name='Самая популярная оценка'),
        ),
        migrations.AlterField(
            model_name='eventrating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (1, 'Зачет'), (0, 'Незачет')], help_text='Оценка: 1-5 для пятибалльной системы, 0-незачет/1-зачет для зачетной системы', verbose_name='Оценка'),
        ),
    ]
