# Generated by Django 5.2.9 on 2026-01-29 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('stats', '0003_eventrating_grading_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrating',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к оценке'),
        ),
        migrations.AddField(
            model_name='eventrating',
            name='offline_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.offlinesessionsinfo', verbose_name='Оффлайн-сессия'),
        ),
        migrations.AddField(
            model_name='eventrating',
            name='online_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.onlineeventinfo', verbose_name='Онлайн-сессия'),
        ),
    ]
