# Generated by Django 5.2.9 on 2026-01-29 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('stats', '0004_eventrating_comment_eventrating_offline_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventrating',
            unique_together={('event', 'participant', 'referee'), ('offline_session', 'participant', 'referee'), ('online_session', 'participant', 'referee')},
        ),
        migrations.AddIndex(
            model_name='eventrating',
            index=models.Index(fields=['online_session'], name='stats_event_online__1c6027_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrating',
            index=models.Index(fields=['offline_session'], name='stats_event_offline_d83bd9_idx'),
        ),
    ]
