# Generated by Django 5.2.9 on 2026-01-29 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('stats', '0005_alter_eventrating_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventrating',
            name='stats_event_event_i_ad6ea3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='eventrating',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='eventrating',
            index=models.Index(fields=['event', 'participant', 'referee'], name='stats_event_event_i_00461d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrating',
            index=models.Index(fields=['online_session', 'participant', 'referee'], name='stats_event_online__27580a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrating',
            index=models.Index(fields=['offline_session', 'participant', 'referee'], name='stats_event_offline_ee8075_idx'),
        ),
    ]
