# Generated by Django 5.2.9 on 2026-01-29 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('stats', '0006_remove_eventrating_stats_event_event_i_ad6ea3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstatistics',
            name='count_fail',
        ),
        migrations.RemoveField(
            model_name='eventstatistics',
            name='count_grade_1',
        ),
        migrations.RemoveField(
            model_name='eventstatistics',
            name='count_grade_2',
        ),
        migrations.RemoveField(
            model_name='eventstatistics',
            name='count_grade_3',
        ),
        migrations.RemoveField(
            model_name='eventstatistics',
            name='count_grade_4',
        ),
        migrations.RemoveField(
            model_name='eventstatistics',
            name='count_grade_5',
        ),
        migrations.RemoveField(
            model_name='eventstatistics',
            name='count_pass',
        ),
        migrations.RemoveField(
            model_name='eventstatistics',
            name='most_popular_grade',
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_fail_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество незачетов по всему событию'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_1_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 1 по всему событию'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_2_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 2 по всему событию'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_3_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 3 по всему событию'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_4_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 4 по всему событию'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_grade_5_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок 5 по всему событию'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='count_pass_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество зачетов по всему событию'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='most_popular_grade_total',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Наиболее часто встречающаяся оценка по всему событию', null=True, verbose_name='Самая популярная оценка по всему событию'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='session_averages',
            field=models.JSONField(default=dict, help_text='Словарь с ID сессии как ключом и средним баллом как значением', verbose_name='Средние баллы по сессиям'),
        ),
        migrations.AddField(
            model_name='eventstatistics',
            name='session_grade_distribution',
            field=models.JSONField(default=dict, help_text='Словарь с ID сессии как ключом и статистикой оценок как значением', verbose_name='Распределение оценок по сессиям'),
        ),
        migrations.AlterField(
            model_name='eventstatistics',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Средний арифметический балл всех участников по всему событию', max_digits=3, null=True, verbose_name='Средний балл по всему событию'),
        ),
        migrations.CreateModel(
            name='EventParticipantStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_scores_count', models.JSONField(default=dict, help_text='Словарь с ID сессии как ключом и количеством оценок как значением', verbose_name='Количество оценок по сессиям')),
                ('final_score', models.FloatField(blank=True, help_text='Среднее арифметическое по всем сессиям, округленное в большую сторону', null=True, verbose_name='Итоговая оценка участника')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Средний балл участника по всем сессиям')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Дата расчета статистики')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_statistics', to='events.event', verbose_name='Событие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='events.eventparticipant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Статистика участника события',
                'verbose_name_plural': 'Статистики участников событий',
                'ordering': ['-calculated_at'],
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
