# Generated by Django 5.2.9 on 2026-01-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_remove_eventstatistics_count_fail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipantstatistics',
            name='most_popular_grades',
            field=models.CharField(blank=True, help_text='Перечень самых популярных оценок участника, разделенных запятой', max_length=100, null=True, verbose_name='Самые популярные оценки участника'),
        ),
    ]
