# Generated by Django 5.2.9 on 2026-01-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_eventparticipantstatistics_most_popular_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatistics',
            name='most_popular_grade_total',
            field=models.CharField(blank=True, help_text='Перечень самых популярных оценок по всему событию, разделенных запятой', max_length=100, null=True, verbose_name='Самые популярные оценки по всему событию'),
        ),
    ]
